[package]
name = "biomer"
version = "0.1.0"
authors = ["Anatoly Baranov <anatoly.baranov@tomtom.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
bmp = "0.5" # for debugging